server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://192.168.2.101:3306/your_database_name
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml