server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://10.211.55.8:3306/myDb
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 10.211.55.8
    port: 6379
    password: root123

mybatis:
  mapper-locations: classpath:/mapper/*.xml